apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: yolo-client
        image: adrianapindi/yolo-client:v1.0.0 
        ports:
        - containerPort: 80
