---
- name: Pull image from repository
  docker_image:
    name: adrianapindi/yolo-backend:v1.3.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: adih-yolo-backend
    image: adrianapindi/yolo-backend:v1.3.0
    networks:
      - name: yolo-net
    ports:
      - "5000:5000"
    command: "npm start"
    env:
      MONGODB_URI: "mongodb://app-mongo:27017/yolomy"
  become: yes