---
- name: Deploy Node.js Backend Container
  docker_container:
    name: adih-yolo-backend
    image: adrianapindi/yolo-backend:v1.3.0
    networks:
      - name: yolo-net
    ports:
      - "5000:5000"
    command: "npm start"
    env:
      MONGODB_URI: "mongodb://192.168.56.13:27017/yolomy"
    restart_policy: always   
    state: started          
  become: yes